---
- name: setup webserver vhost
  hosts: all
  become: true
  vars:
    app_user: "www-data"
    http_host: "{{ http_port }}example.com"
    http_conf: "{{ http_port }}example.com.conf"
    http_port: "8185"
    disable_default: true
  tasks:
    - name: add port number to apache2
      lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen {{ http_port }}


    - name: document root exist
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: custom index.html
      ansible.builtin.copy:
        dest: "/var/www/{{ http_host }}/index.html"
        content: |
                    Custom Web Page

    - name: set up Apache virtualhost
      ansible.builtin.template:
        src: "apache.conf.j2"
        dest: "/etc/apache2/sites-enabled/{{ http_conf }}"


    - name: open firewall
      community.general.ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
    

    - name: Apache restart
      service:
        name: apache2
        state: restarted

