---
- hosts: all
  remote_user: jude
  tasks:
     - name: Change Time Zone to Tokyo
       become: yes
       ansible.builtin.shell: timedatectl set-timezone Asia/Tokyo
     
     
     - name: install basic tools
       become: yes
       apt:
         pkg:
           - vim
           - unzip
           - htop
           - net-tools
           - curl  
 


     







#ansible.builtin.shell: "timedatectl set-timezone Asia/Tokyo"
