---


- hosts: all
  become: true
    
  tasks:
  - name: create sim6
    tags: always
    ansible.builtin.user:
      name: sim6
      shell: /bin/bash  
      group: sudo 
  
  - name: add ssh key for sim6
    tags: always
    authorized_key:
      user: sim6
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqs8tKS3Jiw7MVbISjJ0nPrl98bepkz4e/ImCpMVhgzuBvfIzWTi6FCvEcvKgtPpHEyL5h98aVJXDohmnFIijXdVhXz7rToGecm+2tkJNv0DS3sV6zePqFp3+SzeKhrIKNR2Uc0c3uc1gA3nSj2x9kL6s4ibW2mWVenX0qJdzqSMI5d054jbyaUinEMNIJx+cQvNafuscvIeDe+pkl3aYs51pY6hxE09WaiHPD0zf3w3uYvP0MZmkseLiRKjLBV2Fu5ABmegxfvXPe5QYY+e3vKxyIdsZRJMdzvsr3xsFRc1AC/q76H+cwT2ahnnqTCsECIuS1J49/RxsUanG7BaAD sim3" 

  - name: add sudouser for sim6
    tags: always
    copy:
      src: sudoer_sim5
      dest: /etc/sudoers.d/sim6
      owner: root
      group: root
      mode: 0440  
