- hosts: all
  become: yes
  tasks:
    - name: Installation php8 dependencies
      apt: 
        pkg:
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common  

    - name: "Repo PHP 8.0"
      apt_repository:
        repo="ppa:ondrej/php"
        
   

    - name: Installation PHP 8.0
      apt: name=php8.0 state=present

    - name: install lamp stack
      apt:
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes 
