---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_disribution == "Ubuntu"
  
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansibel_distribution == "CentOS" 


- hosts: web_servers
  become: true
  tasks:

  - name: install apache & php
    tags: web,apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansibel_distribution == "Ubuntu"    
  - name: copy default html file
    tags: web,apache2
    copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  


      
